apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-bdng
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-bdng
    app.kubernetes.io/part-of: test-app-jxdl
  name: devfile-sample-python-basic-bdng
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-bdng
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-bdng
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-flij-tenant/test-app-jxdl/devfile-sample-python-basic-bdng@sha256:8e791751269a24c0a1fd39c82ef2ee7f731b5d2dc014505668d51217c0ce454b
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
